version: "3.6"
services:
  lending_application:
    ports:
      - 8080:8080
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: lending_application
